export { Footer } from './atoms/footer/Footer'
export { Pagination } from './atoms/pagination/Pagination'
export { ScrollArrow } from './atoms/scrollArrow/ScrollArrow'
export { SearchInput } from './atoms/searchInput/SearchInput'
export { Image } from './atoms/image/Image'
export { Icon } from './atoms/icon/Icon'
export { Slider } from './atoms/slider/Slider'

export { Banner } from './molecules/banner/Banner'
export { Header } from './molecules/header/Header'
